### ISSUE TITLE
Resolved: Q3... any problem?

### ISSUE THREAD

**Issue by pma2** [LDSSA/batch2-BLU05#4]
I am not being able to get the correct result in Q3... any clues?
Seems that I am doing the correct query that... **counts the number of movies that have a caracter whose name is "Maria" or "Maria something else"**
But assert fails.
Thanks

**Comment by dominguezmaria** [comment]
Hi @pma2 !
So, the questions asks to count all the characters named "Maria" or "Maria something else".
On the second case, note the space between "Maria" and the "something else".

Some examples:
"Maria" -> should be **included**
"Marianne" -> should be **excluded**
"Maria Theresa" -> should be **included**
"Maria Sophia Coletta Ragetti" -> should be **included**

Hope this helps!

**Comment by pma2** [comment]
Thanks, is already working ;)
