### ISSUE TITLE
Q5 bug

### ISSUE THREAD

**Issue by ivanrvpereira** [LDSSA/batch2-BLU05#6]
I think you have a bug on this question.

On the second variable `most_western_actor_movies_count`, the actor appeared minus 1 time because in one particular movie the actor made two characters.

**Comment by dominguezmaria** [comment]
Hi @balsagoth , thank you for catching this bug, it seems you are right.

So, for everyone, in order for your answer to be accepted in nbgrader, if the actor plays two characters in the same movie, it should count twice in most_western_actor_movies_count.

In other words, what we're really asking is **how many characters did the actor play in Western movies**.
